"""add_ml_registry_and_forecast_tables

Revision ID: 478e112a9ef6
Revises: 980813bae3f2
Create Date: 2026-04-13 09:19:07.346632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '478e112a9ef6'
down_revision: Union[str, Sequence[str], None] = '980813bae3f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('input_data', sa.String(), nullable=False),
    sa.Column('predictions', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ml_model_registry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('model_type', sa.String(), nullable=False),
    sa.Column('training_date', sa.DateTime(), nullable=False),
    sa.Column('mae', sa.Float(), nullable=False),
    sa.Column('rmse', sa.Float(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('parameters', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ml_model_registry')
    op.drop_table('forecast_scenarios')
    # ### end Alembic commands ###
